import json
import os
from datetime import datetime
from pathlib import Path

import requests
import streamlit as st
from dotenv import load_dotenv


load_dotenv()

BASE_DIR = Path(__file__).resolve().parent
PROMPT_PATH = BASE_DIR / "prompts" / "incident_triage_prompt.txt"
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
DEFAULT_MODEL = os.getenv("OLLAMA_MODEL", "llama3.1")


def load_prompt():
    """Load the reusable SOC analyst prompt from disk."""
    try:
        return PROMPT_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        return (
            "You are a SOC analyst. Review the JSON alert and return a clear, "
            "defensive incident triage report."
        )


def detect_alert_source(alert_json):
    """Best-effort detection for supported cybersecurity alert sources."""
    if not isinstance(alert_json, dict):
        return "Unknown"

    lowered_keys = {str(key).lower() for key in alert_json.keys()}
    raw_text = json.dumps(alert_json).lower()

    if "prowler" in raw_text or {"status", "check_id", "service_name"} <= lowered_keys:
        return "Prowler"

    if (
        "guardduty" in raw_text
        or alert_json.get("source") == "aws.guardduty"
        or "service" in lowered_keys
        and "severity" in lowered_keys
        and "finding" in raw_text
    ):
        return "AWS GuardDuty"

    if (
        alert_json.get("eventSource")
        or alert_json.get("eventName")
        or alert_json.get("eventType")
        or "cloudtrail" in raw_text
    ):
        return "AWS CloudTrail"

    if (
        "wazuh" in raw_text
        or "rule" in lowered_keys
        and "agent" in lowered_keys
        or "win" in lowered_keys
        or "decoder" in lowered_keys
    ):
        return "Wazuh"

    return "Unknown"


def call_ollama(prompt, model_name):
    """Send a prompt to the local Ollama generate API and return the model text."""
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
    }

    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=120)
    except requests.exceptions.ConnectionError as exc:
        raise RuntimeError("Ollama is not running. Start it with: ollama serve") from exc
    except requests.exceptions.Timeout as exc:
        raise RuntimeError("Ollama took too long to respond. Try again or use a smaller model.") from exc

    if response.status_code == 404:
        raise RuntimeError(f"Model not found. Pull it with: ollama pull {model_name}")

    try:
        response.raise_for_status()
    except requests.exceptions.HTTPError as exc:
        error_text = response.text.strip()
        if "not found" in error_text.lower() or "pull" in error_text.lower():
            raise RuntimeError(f"Model not found. Pull it with: ollama pull {model_name}") from exc
        raise RuntimeError(f"Ollama returned an error: {error_text}") from exc

    data = response.json()
    return data.get("response", "").strip()


def generate_incident_report(alert_json, model_name):
    """Build the triage prompt and generate an analyst-style report."""
    alert_source = detect_alert_source(alert_json)
    prompt_template = load_prompt()
    formatted_alert = json.dumps(alert_json, indent=2, sort_keys=True)

    prompt = (
        prompt_template.replace("{{ALERT_SOURCE}}", alert_source).replace(
            "{{ALERT_JSON}}", formatted_alert
        )
    )

    report_text = call_ollama(prompt, model_name)

    if not report_text:
        raise RuntimeError("Ollama returned an empty response. Try again with a different model.")

    return report_text


def export_markdown(report_text, alert_source):
    """Create a downloadable Markdown report with a friendly filename."""
    safe_source = alert_source.lower().replace(" ", "_").replace("/", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"threatbrief_{safe_source}_{timestamp}.md"
    markdown = (
        f"<!-- Generated by ThreatBrief AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->\n\n"
        f"{report_text.strip()}\n"
    )
    return filename, markdown


def parse_json_input(pasted_text, uploaded_file):
    """Parse JSON from upload first, then from pasted text."""
    if uploaded_file is not None:
        try:
            return json.load(uploaded_file)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Uploaded file is not valid JSON: {exc}") from exc

    if pasted_text and pasted_text.strip():
        try:
            return json.loads(pasted_text)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Pasted content is not valid JSON: {exc}") from exc

    raise ValueError("Paste a JSON alert or upload a .json file to begin.")


def render_sidebar():
    """Render settings and beginner-friendly run hints."""
    st.sidebar.header("Settings")
    model_name = st.sidebar.text_input(
        "Ollama model",
        value=DEFAULT_MODEL,
        help="Try llama3.1, mistral, or phi after pulling the model with Ollama.",
    )

    st.sidebar.divider()
    st.sidebar.subheader("Local Ollama")
    st.sidebar.code("ollama serve\nollama pull llama3.1", language="powershell")
    st.sidebar.caption(f"API endpoint: {OLLAMA_URL}")
    return model_name.strip() or DEFAULT_MODEL


def main():
    st.set_page_config(page_title="ThreatBrief AI", layout="wide")

    model_name = render_sidebar()

    st.title("ThreatBrief AI")
    st.caption("Local AI-powered cybersecurity alert triage for defensive SOC workflows.")

    left_col, right_col = st.columns([1, 1])

    with left_col:
        st.subheader("Alert Input")
        uploaded_file = st.file_uploader("Upload a JSON alert", type=["json"])
        pasted_text = st.text_area(
            "Or paste JSON alert",
            height=320,
            placeholder='{\n  "eventName": "CreateUser",\n  "eventSource": "iam.amazonaws.com"\n}',
        )

        analyze_clicked = st.button("Generate Incident Brief", type="primary")

    with right_col:
        st.subheader("Parsed Alert")
        st.info("Submit an alert to preview source detection and formatted JSON.")

    if not analyze_clicked:
        return

    try:
        alert_json = parse_json_input(pasted_text, uploaded_file)
    except ValueError as exc:
        st.error(str(exc))
        return

    alert_source = detect_alert_source(alert_json)

    with right_col:
        st.metric("Detected Source", alert_source)
        st.json(alert_json, expanded=True)

    with st.spinner(f"Asking local Ollama model '{model_name}' to triage the alert..."):
        try:
            report_text = generate_incident_report(alert_json, model_name)
        except RuntimeError as exc:
            st.error(str(exc))
            return

    st.divider()
    st.subheader("Incident Report")
    st.markdown(report_text)

    filename, markdown = export_markdown(report_text, alert_source)
    st.download_button(
        "Export Markdown Report",
        data=markdown,
        file_name=filename,
        mime="text/markdown",
    )


if __name__ == "__main__":
    main()
